services:
  - type: worker
    name: rks-telegram-bot
    env: python
    plan: free
    buildCommand: python -m pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python bot.py